version: "3"

services:

  #Disable systemd-resolved service and configure /etc/resolv.conf for the host before using ports 53
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    env_file:
      - ".env"
    environment:
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9090:80/tcp"
    volumes:
      - "./pihole/etc-pihole:/etc/pihole"
      - "./pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped

  nessus:
    container_name: nessus
    image: tenableofficial/nessus:latest
    hostname: nessus
    env_file:
      - ".env"
    environment:
      USERNAME: ${NESSUS_USERNAME}
      PASSWORD: ${NESSUS_PASSWORD}
      ACTIVATION_CODE: ${NESSUS_ACTIVATION_CODE}
    ports:
      - "8834:8834/tcp"
    restart: unless-stopped

  splunk:
    container_name: splunk
    image: splunk/splunk:latest
    hostname: splunk
    env_file:
      - ".env"
    environment:
      - SPLUNK_START_ARGS:${SPLUNK_START_ARGS}
      - SPLUNK_PASSWORD:${SPLUNK_PASSWORD}
    ports:
      - "8000:8000/tcp"
      - "9997:9997/tcp"
      - "8088:8088/tcp"
      - "1514:1514/tcp"
    volumes:
      - "./splunk/etc:/opt/splunk/etc"
      - "./splunk/var:/opt/splunk/var"
      - "./splunk/import:/opt/splunk/import"
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    hostname: portainer
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./portainer/portainer-data:/data"
    ports:
      - "9000:9000/tcp"
    restart: unless-stopped

  ansible:
    container_name: ansible
    image: ubuntu:latest
    hostname: ansible
    user: root
    volumes:
      - "./ansible/hosts:/etc/ansible/hosts"
      - "./ansible:/root/ansible/files"
    command:  /bin/bash -c 
      "echo 'nameserver 8.8.8.8' > /etc/resolv.conf 
      && apt-get update
      && apt-get install ansible ssh vim netplan.io net-tools -y
      && service ssh start
      && ssh-keygen -b 4096 -t rsa -N '' -f '/root/.ssh/id_rsa' <<<y
      && tail -f /dev/null" #Keep the container running
    restart: unless-stopped
